services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 9999:8080
    environment:
      WEBUI_SECRET_KEY: "secret-key-1234"
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"

  open-webui-pipelines:
    profiles: [pipelines]
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - open-webui
    volumes:
      - pipelines:/app/pipelines
    restart: unless-stopped
    ports:
      - "9099:9099"
    env_file: ".env"

volumes:
  open-webui: {}
  pipelines: {}
